version: '3.3'

services:

  alpine-nginx:
    build: ./nginx_alpine
    container_name: alpine-nginx
    ports:
        - "80:80"
    volumes:
        - ./app/src:/var/www
        - ./nginx_alpine/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx_alpine/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    restart : always
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=itelis_test
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
    volumes:
    - ./db:/var/lib/postgresql/data

  php:
    container_name: php
    build: ./php-app
    volumes:
        - ./app/src:/var/www
        - ./php-app/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./php-app/php.ini:/etc/php7/php.ini
    links:
        - postgres:postgres
    tty: true
   # environment:
   #     - drupal_data_name=itelis_test
   #     - drupal_data_user=root
   #     - drupal_data_password=root
   #     - drupal_data_host=postgres
   #     - drupal_data_port=5432


#  drupal:
#    image: drupal:8.7
#    ports:
#        - 8080:80
#    volumes:
#        - /var/www/html/modules
#        - /var/www/html/profiles
#        - /var/www/html/themes
#        - /var/www/html/sites
#    restart: always
